export type { tHashTypeList };
export { HASH_TYPE_LIST, HASH_TYPE_DEFAULT, SALT_NOT_ALLOWED_CHAR, ROUNDS_MAX, ROUNDS_MIN, ROUNDS_DEFAULT };

const SALT_NOT_ALLOWED_CHAR = /[^\.\/0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz]/;

const ROUNDS_DEFAULT = 5000;
const ROUNDS_MIN = 1000;
const ROUNDS_MAX = 999999999;

const HASH_TYPE_LIST = ["SHA-512"] as const;
type tHashTypeList = typeof HASH_TYPE_LIST[number];
const HASH_TYPE_DEFAULT = "SHA-512";
